### ISSUE TITLE
[PMS] Non-Hacker Check In Fixes

### ISSUE THREAD

**Issue by samderanova** [HackAtUCI/irvinehacks-site-2024#371] opened 2024-01-26 22:30 UTC
Following from #368, we need to fix the disable condition for `confirmButton` to match its corresponding condition for showing `ParticipantActionPopover`. Additionally, we can simply the `confirm_attendance_non_hacker` function to use `update_one` instead of `raw_update_one`.

**Comment by taesungh** [comment] 2024-01-26 22:34
Partial duplicate of #370?

**Closed** 2024-01-26 23:23 UTC
